server:
  servlet:
    contextPath: /
    session:
      persistent: true
  port: 8094

spring:
  application:
    name: cql-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

springdoc:
  packagesToScan: com.mdtlabs.coreplatform.cqlservice
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
    configUrl: /cql/swagger-ui/v3/api-docs/swagger-config
    url: /cql/swagger-ui/v3/api-docs
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
    path: /cql/swagger-ui/v3/api-docs

app:
  fhir-server-url: ${HAPI_SERVER_URL}
  cql-path: ${CQL_PATH}
  valueset-path: ${VALUESET_PATH}

spicelog:
  fileName: './log/SpiceApplicationLog.log'
  fileNamePattern: './log/SpiceApplicationLog.%d{yyyy-MM-dd}.log.gz'
  consolePattern: '%white(%d{ISO8601}) %highlight(%-5level) [%yellow(%t)] :  %msg%n%throwable'
  filePattern: ' %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  maxHistory: 30
  totalSizeCap: 3GB
