server:
  servlet:
    #contextPath: /shorturl-service
    contextPath: /
  port: 8095
#DB Config
spring:
  application:
    name: shorturl-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username : ${DATABASE_USERNAME}
    password : ${DATABASE_PASSWORD}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jpa:
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
app:
  domain: ${SHORTEN_URL_DOMAIN}

spicelog:
  fileName: './log/SpiceApplicationLog.log'
  fileNamePattern: './log/SpiceApplicationLog.%d{yyyy-MM-dd}.log.gz'
  consolePattern: '%white(%d{ISO8601}) %highlight(%-5level) [%yellow(%t)] :  %msg%n%throwable'
  filePattern: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  maxHistory: 30
  totalSizeCap: 3GB